apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'false'
  labels:
    app: gugotik-video-service
  name: gugotik-video-service
  namespace: gugotik-service-bundle
spec:
  selector:
    matchLabels:
      name: gugotik-video-service
  template:
    metadata:
      labels:
        app: gugotik-video-service
        branch: master
        version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
        name: gugotik-video-service
        dream-app: gugotik-video-service
        dream-unit: gugotik-video-service
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: storage
      imagePullSecrets:
        -   name: reg-cred
      containers:
        -   image: ${IMAGE}
            imagePullPolicy: IfNotPresent
            name: gugotik-video-service
            command:
              - ./services/videoprocessor/VideoprocessorService
            envFrom:
              -   configMapRef:
                    name: env-config
              - configMapRef:
                  name: gugotik-env
              - secretRef:
                  name: gugotik-secret
            ports:
              - name: grpc-37001
                containerPort: 37001
                protocol: TCP
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 8Mi
            volumeMounts:
              - mountPath: /data/apps/gugotik-service-bundle/data
                name: volume
      terminationGracePeriodSeconds: 30